site_name: Open Banking Gateway Documentation
repo_url: https://github.com/adorsys/open-banking-gateway
site_description: Provides tools, adapter and connector for transparent access to open banking apis
strict: true
nav:
  - Home: README.md
  - "Getting started": getting_started.md
  - "Contibution Guidelines": ContributionGuidelines.md
  - "Roadmap": roadmap.md
  - "Release notes": releasenotes.md
  - "Version policy": version_policy.md
  - "Initial Requirements": architecture/drafts/initial_requirements.md
  - "Architecture":
      - "Dictionary": architecture/dictionary.md
      - "Application context": architecture/building_blocks/01.Application_context.md
      - "Component diagrams": architecture/building_blocks/02.Component_diagrams.md
  - "Concepts":
      - "PSU Security Concept": architecture/concepts/psu-security-concept.md
  - "Use cases":
      - "Use cases": architecture/use_cases.md
      - "Login with FinTech Application": architecture/1-loginWithFinTech.md
      - "Search bank": architecture/2-searchBank.md
      - "Select bank": architecture/3-selectBank.md
      - "List of Accounts": architecture/4a-aisListOfAccounts.md
      - "List of Transactions": architecture/4b-aisListOfTransactions.md
      - "Redirect to Consent Authorization API": architecture/5-redirectPsuToConsentAPI.md
      - "Authorize Consent Embedded Approach": architecture/5a-psuAuthEmbeddedConsent.md
      - "Authorize Consent Redirect Approach": architecture/5b-psuAuthRedirectConsent.md
      - "Consume Service": architecture/6-consume_api.md
  - "Draft": architecture/drafts/initial_requirements.md
  - "Initial requirements": initial_requirements.md
theme: readthedocs
