site_name: Open Banking Gateway Documentation
repo_url: https://github.com/adorsys/open-banking-gateway
site_description: Provides tools, adapter and connector for transparent access to open banking apis
nav:
  - Home: README.md
  - "Architecture":
    - "Login with FinTech Application": architecture/1-loginWithFinTech.md
    - "Search bank": architecture/2-searchBank.md
    - "Select bank": architecture/3-selectBank.md
    - "List of Transactions": architecture/4-initiateAisConsent.md
    - "Redirect to Consent Authorization API": architecture/5-redirectPsuToConsentAPI.md
    - "Authorize Consent Embedded Approach": architecture/5a-psuAuthEmbeddedConsent.md
    - "Authorize Consent Redirect Approach": architecture/5b-psuAuthRedirectConsent.md
    - "Consume Service": architecture/6-consume_api.md
    - "Draft": architecture/drafts/initial_requirements.md
  - "Roadmap": roadmap.md
  - "Dictionary": architecture/dictionary.md
  - "Contribution guidelines": ContributionGuidelines.md
  - "Release notes": releasenotes.md
  - "Initial Requirements": initialrequirements.md
  - "Version Policy": version_policy.md
theme: readthedocs
