# Builds daily develop branch using `heavy tests` test suite
name: Develop branch heavy tests daily build

on:
  schedule:
    - cron: '0 9 */1 * *' # 9 AM UTC each day

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Free disk space
        run: |
          sudo apt clean
          docker rmi $(docker image ls -aq)
          echo "Available space"
          df -h

      - name: Build project and run default test suite
        run: |
          ./scripts/build_and_test.sh
        env:
          MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120" # Github-on-Azure tweaks - https://github.com/actions/virtual-environments/issues/1499
          ENABLE_HEAVY_TESTS: true
          MOZ_HEADLESS: 1

