# Builds pushes and merges on develop branch
name: Develop branch build

default-env: &default-env
  MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120" # Github-on-Azure tweaks - https://github.com/actions/virtual-environments/issues/1499

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project and run default test suite
        run: ./scripts/build_and_test.sh
        env:
          << : *default-env

      - name: Check deployment flow and check artifact signing
        run: ./scripts/mvn_deploy_check_develop.sh
        env:
          << : *default-env
          # Note that these BELOW are DEVELOP secrets, not ones used for real deployment
          # They are used to have very close pipeline to one present on production
          GPG_EXECUTABLE: gpg
          GPG_PASSPHRASE: ${{ secrets.DEVELOP_GPG_PASSPHRASE }}
          GPG_SECRET_KEY: ${{ secrets.DEVELOP_GPG_SECRET_KEY }}
          GPG_OWNERTRUST: ${{ secrets.DEVELOP_GPG_OWNERTRUST }}
          MOZ_HEADLESS: 1

      - name: Build FireFly improter
        run: ./scripts/build_firefly_exporter_mvn.sh
        env:
          <<: *default-env

      - name: Deploy develop artifacts to OpenShift
        run: ./scripts/deploy_openshift.sh scripts/service.list
        env:
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Deploy FireFly-importer to OpenShift
        run: ./scripts/deploy_openshift.sh scripts/firefly-service.list
        env:
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Upload coverage to CodeCov
        run: ./scripts/upload_coverage_to_codecov.sh

      - name: Update GitHub pages
        run: ./scripts/deploy_doc.sh
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate OpenShift DEV env deployment status
        run: ./scripts/validate_dev_deploy.sh
        env:
          <<: *default-env
          MOZ_HEADLESS: 1
