# Builds manually develop branch using `heavy tests` test suite
name: Develop or custom branch heavy tests MANUAL build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'
        required: true
        default: 'develop'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Free disk space
        run: |
          sudo apt clean
          docker rmi $(docker image ls -aq)
          docker system prune -af
          echo "Available space"
          df -h

      - name: Build project and run default test suite
        run: |
          (while true; do df -h; sleep 60; done;) &
          ./scripts/build_and_test.sh
        env:
          MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120" # Github-on-Azure tweaks - https://github.com/actions/virtual-environments/issues/1499
          ENABLE_HEAVY_TESTS: true
          MOZ_HEADLESS: 1

