# Builds pushes of release candidate tags
name: Release candidate promotion to production

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Promote artifacts from OpenShift to DockerHub
        run: ./scripts/promote_oc_image_to_dockerhub.sh
        env:
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          RELEASE_CANDIDATE_DOMAIN: openshift-registry.adorsys.de
          RELEASE_CANDIDATE_PROJECT_NAME: open-banking-gateway-integ

      - name: Promote release-candidate JARs to Maven-central
        run: ./scripts/deploy_mvn.sh
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          # These are required for READ access to Github Packages maven:
          STAGE_ARTIFACTORY_USERNAME: ${{ github.actor }}
          STAGE_ARTIFACTORY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GIT_BRANCH: master # Force branch to resolve to master if git resolution fails - otherwise gitflow-helper uses UNDEFINED branch

      -name: Release JavaDocs
      - run: ./scripts/deploy_javadoc.sh
        env:
          - GITHUB_ACTOR: ${{ github.actor }}
          - GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
